site_name: Gothic Modding Community

theme:
  name: material
  logo: img/gmc_logo.png
  palette:
    primary: black
  features:
    - navigation.sections

nav:
  - Home: index.md
  - ZenGin (G1/G2):
    - General information:
      - Directory structure: DirectoryStructure.md
      - VDFS - virtual file system :
        - Virtual file system : VDFS.md
        - GothicVDFS : GothicVDFS.md
        - VDFS Tool : VDFSTool.md
      - Object persistence: ObjectPersistence.md
    - Animations:
      - Overview: Animation.md
      - MDS - ModelScript: MDS.md
      - EventBlocks: AniEventBlocks.md
      - Tutorials:
        - Standalone animation: StandaloneAni.md
    - Meshes:
      - Overview: Meshes.md
    - Music:
      - Overview: Music.md
    - Sound:
      - Overview: Sound.md
    - Textures:
      - Overview: Textures.md
    - Video:
      - Overview: Video.md
    - Worlds:
      - Overview: Worlds.md
    - Daedalus:
      - Overview: Scripts.md
      - Classes:
        - C_ITEM: c_item.md
    - Union plugins:
      - zParserExtender:
        - Overview: zParserExtender.md
        - Extensions and Externals: 
          - While loop: zPE_while.md
          - Namespaces: zPE_namespaces.md
          - Event functions: zPE_events.md
          - C_Trigger class: zPE_c_trigger.md
          - External functions: zPE_externals.md
        - Injection:
          - Overview: zPE_injection.md
          - META block: zPE_META.md
          - Hooking: zPE_hooks.md
          - Other features: zPE_other.md
  - Genome (G3/R1):
    - General information:
      - Genome engine: Genome.md
      - Object persistence: GenomeObjectPersistence.md



markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
