site_name: Gothic Modding Community

theme:
  name: material
  logo: img/gmc_logo.png
  palette:
    primary: black
  features:
    - navigation.sections
    - navigation.indexes 

nav:
  - Home: index.md
  - ZenGin (G1/G2):
    - General information:
      - Directory structure: zengin/general_info/DirectoryStructure.md
      - VDFS - virtual file system : 
        - zengin/general_info/vdfs/index.md
        - GothicVDFS : zengin/tools/GothicVDFS.md
        - VDFS Tool : zengin/tools/VDFSTool.md
      - Object persistence: zengin/general_info/ObjectPersistence.md

    - Animations: 
      - zengin/anims/index.md
      - MDS - ModelScript: zengin/anims/MDS.md
      - EventBlocks: zengin/anims/AniEventBlocks.md
      - Tutorials:
        - Standalone animation: zengin/anims/StandaloneAni.md

    - Meshes: 
      - zengin/meshes/index.md

    - Music: 
      - zengin/music/index.md

    - Sound:
      - zengin/sound/index.md

    - Textures:
      - zengin/textures/index.md

    - Video:
      - zengin/video/index.md

    - Worlds:
      - zengin/worlds/index.md

    - Scripts: 
      - zengin/scripts/index.md
      - Classes:
        - C_ITEM: zengin/scripts/classes/c_item.md

    - Union plugins:
      - zengin/union_plugins/index.md
      - zParserExtender:
        - zengin/union_plugins/zParserExtender/index.md
        - Extensions and Externals: 
          - While loop: zengin/union_plugins/zParserExtender/zPE_while.md
          - Namespaces: zengin/union_plugins/zParserExtender/zPE_namespaces.md
          - Event functions: zengin/union_plugins/zParserExtender/zPE_events.md
          - C_Trigger class: zengin/union_plugins/zParserExtender/zPE_c_trigger.md
          - External functions: zengin/union_plugins/zParserExtender/zPE_externals.md
        - Injection:
          - zengin/union_plugins/zParserExtender/zPE_injection.md
          - META block: zengin/union_plugins/zParserExtender/zPE_META.md
          - Hooking: zengin/union_plugins/zParserExtender/zPE_hooks.md
          - Other features: zengin/union_plugins/zParserExtender/zPE_other.md

    - Tools:
      - zengin/tools/index.md
      - Daedalus:
        - Daedalus Language Server: zengin/tools/DLS.md
      - VDFS tools:
        - GothicVDFS: zengin/tools/GothicVDFS.md
        - VDFS Tool: zengin/tools/VDFSTool.md

  - Genome (G3/R1):
    - General information: 
      - genome/index.md
      - Object persistence: genome/ObjectPersistence.mdf



markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
