site_name: Gothic Modding Community
site_url: https://auronen.github.io/gmc/

repo_name: auronen/gmc
repo_url: https://github.com/auronen/gmc/
edit_uri: edit/main/docs/

theme:
  name: material
  logo: img/gmc_logo.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: black
      scheme: default
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      accent: light blue
      scheme: slate
      toggle:
        icon: material/brightness-2
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.indexes

nav:
  - Home:
    - index.md
    - Getting Started: GettingStarted_ZenGin.md
    - ZenGin (G1/G2): zengin/general_info/DirectoryStructure.md
    - Genome (G3/R1): genome/index.md
  - ZenGin (G1/G2):
    - General information:
      - Directory structure: zengin/general_info/DirectoryStructure.md
      - VDFS - virtual file system: 
        - zengin/general_info/vdfs/index.md
        - GothicVDFS: zengin/tools/GothicVDFS.md
        - VDFS Tool: zengin/tools/VDFSTool.md
      - Object persistence: zengin/general_info/ObjectPersistence.md

    - Animations: 
      - zengin/anims/index.md
      - MDS - ModelScript: zengin/anims/MDS.md
      - EventBlocks: zengin/anims/AniEventBlocks.md
      - Tutorials:
        - Standalone animation: zengin/anims/StandaloneAni.md

    - Meshes: 
      - zengin/meshes/index.md

    - Music: 
      - zengin/music/index.md

    - Sound:
      - zengin/sound/index.md

    - Textures:
      - zengin/textures/index.md

    - Video:
      - zengin/video/index.md

    - Worlds:
      - zengin/worlds/index.md

    - Scripts: 
      - zengin/scripts/index.md
      - Classes:
        - C_ITEM: zengin/scripts/classes/c_item.md

    - Union plugins:
      - zengin/union_plugins/index.md
      - zParserExtender:
        - zengin/union_plugins/zParserExtender/index.md
        - Extensions and Externals: 
          - While loop: zengin/union_plugins/zParserExtender/zPE_while.md
          - Namespaces: zengin/union_plugins/zParserExtender/zPE_namespaces.md
          - Event functions: zengin/union_plugins/zParserExtender/zPE_events.md
          - C_Trigger class: zengin/union_plugins/zParserExtender/zPE_c_trigger.md
          - External functions: zengin/union_plugins/zParserExtender/zPE_externals.md
        - Injection:
          - zengin/union_plugins/zParserExtender/zPE_injection.md
          - META block: zengin/union_plugins/zParserExtender/zPE_META.md
          - Hooking: zengin/union_plugins/zParserExtender/zPE_hooks.md
          - Other features: zengin/union_plugins/zParserExtender/zPE_other.md

    - Tools:
      - zengin/tools/index.md
      - Daedalus:
        - Daedalus Language Server: zengin/tools/DLS.md
      - VDFS tools:
        - GothicVDFS: zengin/tools/GothicVDFS.md
        - VDFS Tool: zengin/tools/VDFSTool.md

  - Genome (G3/R1):
    - General information: 
      - genome/index.md
      - Object persistence: genome/ObjectPersistence.md


extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mCpS5b5SUY
      name: Gothic Modding Comunity Discord Server
    - icon: fontawesome/brands/github
      link: https://github.com/auronen/gmc
      name: Gothic Modding Comunity Github repository


markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
